"""
Django settings for ETS project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from datetime import timedelta
from pathlib import Path
import os
import mimetypes
from celery.schedules import crontab

# ─── Base Directory ───────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent

# ─── Security ─────────────────────────────────────────────────────────────────
SECRET_KEY = 'django-insecure-!udw6yvg*9h*&nxwocrqp!@oku)gasvvrp$jl4_exp4ez&miaz'

DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '65.108.254.94',
    'q4sconnect_demo.q4s.app',
]

# ─── HTTPS behind nginx / Cloudflare ──────────────────────────────────────────
# nginx (and Cloudflare) terminate TLS and forward the original scheme.
CSRF_TRUSTED_ORIGINS = [
    'https://q4sconnect_demo.q4s.app',
]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ─── Installed Apps ───────────────────────────────────────────────────────────
INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'django_filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',
    'core',
    'opc',

    'django_celery_beat',
]

# ─── Middleware ───────────────────────────────────────────────────────────────
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # MUST be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ─── URL / WSGI ───────────────────────────────────────────────────────────────
ROOT_URLCONF = 'q4s_connect.urls'

WSGI_APPLICATION = 'q4s_connect.wsgi.application'

# ─── Templates ────────────────────────────────────────────────────────────────
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ─── Database ─────────────────────────────────────────────────────────────────
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'mydb'),
        'USER': os.environ.get('POSTGRES_USER', 'admin'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'admin123'),
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# ─── Password Validation ──────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'
    },
]

# ─── Internationalization ─────────────────────────────────────────────────────
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True

# ─── Static Files ─────────────────────────────────────────────────────────────
STATIC_URL = 'static/'

# ─── Custom User Model ────────────────────────────────────────────────────────
AUTH_USER_MODEL = 'accounts.User'

# ─── Django REST Framework ────────────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
        "accounts.permissions.IsActiveUser",
    ),

    "DEFAULT_PAGINATION_CLASS":
        "rest_framework.pagination.PageNumberPagination",

    "PAGE_SIZE": 15,

    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],
}

# ─── Simple JWT ───────────────────────────────────────────────────────────────
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ─── Celery ───────────────────────────────────────────────────────────────────
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE
CELERY_WORKER_CONCURRENCY = 4

CELERY_TASK_IGNORE_RESULT = True

CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_DEFAULT_EXCHANGE = "default"
CELERY_TASK_DEFAULT_ROUTING_KEY = "default"

CELERY_TASK_QUEUES = {
    "default": {
        "exchange": "default",
        "binding_key": "default",
    },

    "opc_scheduler": {
        "exchange": "opc_scheduler",
        "binding_key": "opc_scheduler",
    },

    "opc_polling": {
        "exchange": "opc_polling",
        "binding_key": "opc_polling",
    },
}

CELERY_TASK_ROUTES = {
    "opc.opc_polling_tasks.poll_due_opc_connections": {
        "queue": "opc_scheduler",
        "routing_key": "opc_scheduler",
    },

    "opc.opc_polling_tasks.poll_opc_connection": {
        "queue": "opc_polling",
        "routing_key": "opc_polling",
    },
    "opc.opc_polling_tasks.check_site_connections_health": {
        "queue": "opc_scheduler",
        "routing_key": "opc_scheduler",
    },
    "opc.opc_polling_tasks.calculate_monthly_billings": {
        "queue":       "opc_scheduler",
        "routing_key": "opc_scheduler",
    },
}

CELERY_BEAT_SCHEDULE = {
    "poll-due-opc-connections": {
        "task": "opc.opc_polling_tasks.poll_due_opc_connections",
        "schedule": 60.0,
    },
    "monthly-billing-calculation": {
        "task":     "opc.opc_polling_tasks.calculate_monthly_billings",
        "schedule": crontab(day_of_month=1, hour=0, minute=1),   # 1st of month
    },
    "check-site-connections-health": {
        "task":     "opc.opc_polling_tasks.check_site_connections_health",
        "schedule": 30.0,
    },

}

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_POOL_LIMIT = 10

# ─── CORS Configuration ───────────────────────────────────────────────────────

# Allow Flutter Web localhost random ports
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]

CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "accept",
    "origin",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_CREDENTIALS = True

# ─── Flutter WASM / Frontend ──────────────────────────────────────────────────

# MIME types for Flutter WASM build
mimetypes.add_type("application/wasm", ".wasm", True)
mimetypes.add_type("application/javascript", ".mjs", True)
mimetypes.add_type("application/json", ".json", True)

# Flutter build directory
FRONTEND_DIR = os.path.join(BASE_DIR, 'frontend')

# Allow templates to find Flutter index.html
TEMPLATES[0]['DIRS'].append(FRONTEND_DIR)

# Allow Django staticfiles to serve Flutter assets
STATICFILES_DIRS = [
    FRONTEND_DIR,
]

# ─── OPC Historian Fetch API ─────────────────────────────────────────────────
OPC_HISTORIAN_API_TOKEN = "aaddc77d9a79f00d9e9747baa048de82d38af137a28892538656f76a5aa07060"
OPC_HISTORIAN_HOURS = 2880  # 120 days

# ─── Default Primary Key ──────────────────────────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── External Flutter dashboard app (consumes OPCGeneratedSiteLink URLs) ─────

EXTERNAL_SERVER_UI_BASE_URL = os.environ.get(
    "EXTERNAL_SERVER_UI_BASE_URL",
    "https://q4sconnect_sitemonitoring_demo.q4s.app",
)
EXTERNAL_SERVER_BACKEND_BASE_URL = os.environ.get(
    "EXTERNAL_SERVER_BACKEND_BASE_URL",
    "https://q4sconnect_sitemonitoring_demo.q4s.app",
)